

window.ResourceManager = {
    'Cms_Sitemapchildren_Update_Label' : "Children", 
    'EntityGrid_Url_NotFound' : "A required service URL wasn\u0027t provided.",
    'FileBrowser_Header_Label' : "Choose a file…",
    'ADX_EventSchedule_AcceptableDays' : "Acceptable days",
    'Confirm_DeleteMultiple_Entity' : "Are you sure you want to delete these records?",
    'ADX_Blog_ShortName' : "blog",
    'ADX_BlogPost_ShortName' : "blog post",
    'Entity_Create_ADX_BlogPost_Label' : "Blog post",
    'Entity_Create_ADX_Blog_Label' : "Child blog",
    'Entity_Create_ADX_Event_Label' : "Child event",
    'Entity_Create_ADX_CommunityForum_Label' : "Child forum",
    'Editable_DeleteMultiple_Tooltip_Suffix_Singular' : "Child record?",
    'Editable_DeleteMultiple_Tooltip_Suffix_Plural' : "Child records?",
    'Entity_Create_ADX_Shortcut_Label' : "Child shortcut",
    'ADX_BlogPostComment_ShortName' : "comment",
    'ADX_PageComment_ShortName' : "comment",	
    'Entity_Create_ADX_BlogPost_Tooltip' : "Create a new blog post",
    'Entity_Create_ADX_Blog_Tooltip' : "Create a new child blog",
    'Entity_Create_ADX_Event_Tooltip' : "Create a new child event",
    'Entity_Create_ADX_CommunityForum_Tooltip' : "Create a new child forum",
    'Entity_Create_ADX_Shortcut_Tooltip' : "Create a new child shortcut",
    'Entity_Create_ADX_EventSchedule_Tooltip' : "Create a new event schedule",
    'Entity_Create_ADX_Weblinkset_Tooltip' : "Create a new web link set",
    'Editable_DeleteMultiple_Tooltip_Prefix' : "Delete",
    'Entity_Delete_ADX_Blog_Tooltip' : "Delete this blog",
    'Entity_Delete_ADX_BlogPost_Tooltip' : "Delete this blog post",
    'Entity_Delete_ADX_BlogpostComment_Tooltip' : "Delete this comment",
    'Entity_Delete_ADX_PageComment_Tooltip' : "Delete this comment",
    'Entity_Delete_ADX_Event_Tooltip' : "Delete this event",
    'Entity_Delete_ADX_EventSchedule_Tooltip' : "Delete this event schedule",
    'Entity_Delete_ADX_Webfile_Tooltip' : "Delete this file",
    'Entity_Delete_ADX_CommunityForum_Tooltip' : "Delete this forum",
    'Entity_Delete_ADX_Webpage_Tooltip' : "Delete this page",
    'Entity_Delete_ADX_CommunityForumPost_Tooltip' : "Delete this post",
    'Entity_Delete_ADX_Shortcut_Tooltip' : "Delete this shortcut",
    'Entity_Delete_ADX_CommunityForumThread_Tooltip' : "Delete this thread",
    'SitemapChildren_Update_Tooltip' : "Edit the child records of this page",
    'ADX_Blog_Update_Tooltip' : "Edit this blog",
    'ADX_BlogPost_Update_Tooltip' : "Edit this blog post",
    'ADX_BlogpostComment_Update_Tooltip' : "Edit this comment",
    'ADX_PageComment_Update_Tooltip' : "Edit this comment",
    'ADX_Event_Update_Tooltip' : "Edit this event",
    'ADX_EventSchedule_Update_Tooltip' : "Edit this event schedule",
    'ADX_CommunityForum_Update_Tooltip' : "Edit this forum",
    'ADX_CommunityForumPost_Update_Tooltip' : "Edit this post",
    'ADX_Shortcut_Update_Tooltip' : "Edit this shortcut",
    'ADX_CommunityForumThread_Update_Tooltip' : "Edit this thread",
    'ADX_Event_ShortName' : "event",
    'Entity_Create_ADX_EventSchedule_Label' : "Event schedule",
    'ADX_EventSchedule_ShortName' : "event schedule",
    'ADX_CommunityForum_ShortName' : "forum",
    'ADX_CommunityForumPost_ShortName' : "post",
    'ADX_EventSchedule_Recurrence' : "Recurrence",
    'ADX_Shortcut_Target_Instructions' : "Select a shortcut target. A target URL to an external site must begin with http:// or https://.",
    'ADX_Shortcut_ShortName' : "shortcut",
    'SitemapChildren_HiddenFrom_Sitemap_Tooltip' : "This item is hidden from the site map and won\u0027t appear in navigation elements. It can still be linked to directly.",
    'ADX_Weblink_DisplayPage_Childlinks_Tooltip' : "This web Link is set to display page child links. A child of any child web links shown here won\u0027t be displayed.",
    'ADX_Community_Forum_Thread_ShortName' : "thread",
    'Entity_Form_Select_New' : "+ New",
    'Required_Secure_ViewConfiguration_Not_Provided' : "A required secure ViewConfiguration was not provided.",
    'Click_Stay_To_Save_Your_Changes' : "Your changes haven\u0027t been saved. Would you like to stay on the page to save your changes?",
    'Address_Cannot_Found' : "That address couldn\u0027t be found.",
    'Enter_Address' : "please enter an address",
    'UnKnown_Error_Occurred' : "An unknown error has occurred.",
    'Service_URL_To_Associate_Request_Could_Determined' : "The URL to the service for this Associate Request could determined.",
    'Service_URL_Not_Provided' : "A required service URL wasn\u0027t provided.",
    'Required_Regarding_EntityReference_Parameter_Was_Not_Provided' : "A required regarding AssociatedTableReference parameter was not provided.",
    'URL_Service_For_Add_Note_Request_Could_Not_Determined' : "The URL to the service for this Add Note Request couldn\u0027t be determined.",
    'URL_Service_For_Update_Note_Request_Could_Not_Determined' : "The URL to the service for this Update Note Request couldn\u0027t be determined.",
    'Failed_Determine_RecordID' : "The record ID couldn\u0027t be determined.",
    'Entity_Create_Label' : "New",
    'Entity_Create_Adx_Webfile_Label' : "Child file",
    'Entity_Create_Adx_Webfile_Tooltip' : "Create a new child file",
    'Entity_Create_Adx_Weblink_Tooltip' : "Add a new link",
    'Entity_Create_Adx_Webpage_Label' : "Child page",
    'Entity_Create_Adx_Webpage_Tooltip' : "Create a new child page",
    'Entity_Delete_Adx_Weblink_Tooltip' : "Delete this item",
    'Adx_Webfile_Shortname' : "file",
    'Adx_Webfile_Update_Tooltip' : "Edit this file",
    'Adx_Weblink_Update_Tooltip' : "Edit this link",
    'Adx_Webpage_Shortname' : "page",
    'Adx_Webpage_Not_Yet_Created' : "Not yet created",
    'Pagination_Shortname' : "page",
    'Adx_Webpage_Update_Tooltip' : "Edit this page",
    'Datetimepicker_Datepicker_Label' : "Choose a date",
    'Editable_Cancel_Label' : "Cancel",
    'Editable_Delete_Label' : "Delete",
    'Editable_Delete_Tooltip_Prefix' : "Delete this {0}?",
    'Edit_Label' : "Edit",
    'Edit_Label_Prefix' : "Edit ",
    'Editable_Loading' : "Loading...",
    'Editable_Required_Label' : "(required)",
    'Editable_Save_Label' : "Save",
    'Editable_Saving' : "Saving...",
    'Editable_Sortable_Tooltip' : "Move this item",
    'Editable_Tooltip' : "Edit this content",
    'Error_Dataservice_Default' : "An error has occurred while saving your content. Your changes have not been saved.",
    'Error_Dataservice_Loading' : "An error has occurred while loading content required for this feature.",
    'Error_Dataservice_Loading_Field_Prefix' : "Unable to load ",
    'Confirm_Delete_Entity_Prefix' : "Are you sure you want to delete this {0}?",
    'Confirm_No' : "No",
    'Confirm_Unsavedchanges' : "You have unsaved changes. Do you want to continue?",
    'Confirm_Yes' : "Yes",
    'Validation_Required_Suffix' : "{0} is a required field.",
    'Sitemapchildren_Header_Label' : "Edit children",
    'Answer_Label' : "Answer?",
    'Answered_Label' : "Answered",
    'Approved_Label' : "Approved?",
    'Comment_Policy_Label' : "Comment policy",
    'Content_Disposition_Label' : "Content disposition",
    'Content_Label' : "Content",
    'Content_Language_Label' : "Language content",
    'Copy_Label' : "Copy",
    'Date_Label' : "Date",
    'Description_Label' : "Description",
    'Display_Image_Only_Label' : "Display image only",
    'Enable_Ratings_Label' : "Enable Ratings",
    'Hidden_From_Sitemap_Label' : "Hidden from Sitemap",
    'Image_Height_Label' : "Image height",
    'Locked_Label' : "Locked",
    'Parent_Page_Label' : "Parent page",
    'Partial_URL_Label' : "Partial URL",
    'Published_Label' : "Published",
    'Publishing_State_Label' : "Publishing state",
    'Release_Date_Label' : "Release date",
    'Sticky_Label' : "Sticky",
    'Summary_Excerpt_Label' : "Summary/Excerpt",
    'Tags_Label' : "Tags",
    'Target_Web_Page_Label' : "Target webpage",
    'Thread_Type_Label' : "Thread type",
    'All_Day_Event_Label' : "All day event",
    'Archive_Template_Label' : "Archive template",
    'Custom_CSS_Label' : "Custom CSS",
    'Custom_JavaScript_Label' : "Custom JavaScript",
    'Disable_Page_Validation_Label' : "Disable page validation",
    'Display_Date_Label' : "Display date",
    'Display_Page_Child_Links_Label' : "Display page child links",
    'Editorial_Comments_Label' : "Editorial comments",
    'Enable_Tracking_Label' : "Enable Tracking",
    'End_Time_Label' : "End Time",
    'Entity_List_Label' : "List",
    'Expiration_Date_Label' : "Expiration date",
    'External_URL_Label' : "External URL",
    'Forum_Template_Label' : "Forum Template",
    'Friday_Label' : "Friday",
    'General_Label' : "General",
    'Home_Template_Label' : "Home Template",
    'Image_Alternate_Text_Label' : "Image alternate text",
    'Image_URL_Label' : "Image URL",
    'Image_Width_Label' : "Image width",
    'Interval_Label' : "Interval",
    'Language_Label' : "Language",
    'Language_Label_With_Language' : " - Language: {0}",
    'Location_Name_Label' : "Location name",
    'Max_Recurrences_Label' : "Max recurrences",
    'Monday_Label' : "Monday",
    'Name_Label' : "Name",
    'Open_In_New_Window_Label' : "Open in new window",
    'Options_Label' : "Options",
    'Page_Label' : "Page",
    'Page_Template_Label' : "Page template",
    'Publishing_Label' : "Publishing",
    'R_Label' : "R",
    'Recurrence_Label' : "Recurrence",
    'Recurrence_End_Time_Label' : "Recurrence end time",
    'Registration_Content_Label' : "Registration content",
    'Requires_Registration_Label' : "Requires registration",
    'Robots_Follow_Link_Label' : "Robots follow link",
    'Saturday_Label' : "Saturday",
    'Start_Time_Label' : "Start time",
    'Subject_Label' : "Subject",
    'Summary_Label' : "Summary",
    'Sunday_Label' : "Sunday",
    'Target_Event_Label' : "Target event",
    'Target_Forum_Label' : "Target forum",
    'Target_URL_Label' : "Target URL",
    'Target_Web_File_Label' : "Target web file",
    'Thread_Template_Label' : "Thread template",
    'Thursday_Label' : "Thursday",
    'Title_Label' : "Title",
    'Tuesday_Label' : "Tuesday",
    'Upload_File_Label' : "Upload file",
    'Update_Upload_File_Label' : "Upload file (will replace existing file content)",
    'Web_Form_Label' : "Advanced form",
    'Wednesday_Label' : "Wednesday",
    'Week_Label' : "Week",
    'Templates_Label' : "Templates",
    'Listbox_Label' : "listbox",
    'Insert_Label' : "Insert",
    'Preview_On_Label' : "Preview on",
    'Preview_Off_Label' : "Preview off",
    'Published_UnPublished_Entities_Title' : "Click to toggle preview mode. When on, published and unpublished entities are shown. When off, only published entities can be seen.",
    'Post_Template_Label' : "Post template",
    'Disable_Target_Validation_Label' : "Disable target validation",
    'Cloud_Blob_Address_Label' : "Cloud blob address",
    'Entity_Form_Label' : "Basic Form",
    'Exclude_From_Search_Label' : "Exclude from search",
    'Keywords_Label' : "Keywords",
    'Encoding_Label' : "Encoding",
    'Robots_Label' : "Robots",
    'Author_Label' : "Author",
    'Image_List_Label' : "Image list",
    'Class_Label' : "Class",
    'Source_Label' : "Source",
    'Image_Description_Label' : "Image description",
    'Image_Title_Label' : "Image title",
    'Dimensions_Label' : "Dimensions",
    'Style_Label' : "Style",
    'Horizontal_Space_Label' : "Horizontal space",
    'Vertical_Space_Label' : "Vertical space",
    'Text_To_Display_Label' : "Text to display",
    'Link_List_Label' : "Link list",
    'Target_Label' : "Target",
    'Border_Label' : "Border",
    'Alternative_Source_Label' : "Alternative source",
    'Poster_Label' : "Poster",
    'Find_Label' : "Find",
    'Replace_With_Label' : "Replace with",
    'Border_Color_Label' : "Border color",
    'Background_Color_Label' : "Background color",
    'Cols_Label' : "Cols",
    'Rows_Label' : "Rows",
    'Width_Label' : "Width",
    'Height_Label' : "Height",
    'Cell_Spacing_Label' : "Cell spacing",
    'Cell_Padding_Label' : "Cell padding",
    'Caption_Label' : "Caption",
    'Alignment_Label' : "Alignment",
    'Scope_Label' : "Scope",
    'HAlign_Label' : "H Align",
    'VAlign_Label' : "V Align",
    'Row_Type_Label' : "Row type",
    'Form_Label' : "form",
    'Previous_Edit_Point_Label' : "Previous edit point",
    'Anchors_Label' : "Anchors",
    'Select2_One_Result_Available' : "One result is available. To select it, press Enter.", 
    'Select2_Many_Results_Available' : " results are available, use the Up and Down arrow keys to navigate.", 
    'Select2_No_Matches_Found' : "No matches found", 
    'Select2_Loading_More' : "Loading more results…", 
    'Select2_Searching' : "Searching…",
    'ElFinder_Root_Dir_Not_Exist' : "Root directory does not exists",
    'ElFinder_Error_Connect_Backend' : "Unable to connect to backend",
    'ElFinder_Access_Denied' : "Access denied",
    'ElFinder_Invalid_Bg_Config' : "Invalid backend configuration",
    'ElFinder_Unknown_Cmd' : "Unknown command",
    'ElFinder_Cmd_Not_Allowed' : "Command not allowed",
    'ElFinder_Invalid_Params' : "Invalid parameters",
    'ElFinder_File_Not_Found' : "File not found",
    'ElFinder_Invalid_Name' : "Invalid name",
    'ElFinder_File_Folder_Name_Exist' : "File or folder with the same name already exists",
    'ElFinder_Error_Rename_File' : "Unable to rename file",
    'ElFinder_Error_Create_Folder' : "Unable to create folder",
    'ElFinder_Error_Create_File' : "Unable to create file",
    'ElFinder_No_File_To_Upload' : "No file to upload",
    'ElFinder_Select_File_To_Upload' : "Select at least one file to upload",
    'ElFinder_Maximum_FileSize_Exceeded' : "File exceeds the maximum allowed filesize",
    'ElFinder_Maximum_DataSize_Exceeded' : "Data exceeds the maximum allowed size",
    'ElFinder_File_Type_Not_Allowed' : "Not allowed file type",
    'ElFinder_Error_Upload_File' : "Unable to upload file",
    'ElFinder_Error_Upload_Files' : "Unable to upload files",
    'ElFinder_Error_Remove_File' : "Unable to remove file",
    'ElFinder_Error_Save_Uploaded_File' : "Unable to save uploaded file",
    'ElFinder_Error_Uploading_Files' : "Some files was not uploaded",
    'ElFinder_Error_Copy_Itself' : "Unable to copy into itself",
    'ElFinder_Error_Move_Files' : "Unable to move files",
    'ElFinder_Error_Copy_Files' : "Unable to copy files",
    'ElFinder_Error_FileCopy_Create' : "Unable to create file copy",
    'ElFinder_File_Not_Image' : "File is not an image",
    'ElFinder_Error_Resize_Image' : "Unable to resize image",
    'ElFinder_Error_Write_File' : "Unable to write to file",
    'ElFinder_Error_Create_Archive' : "Unable to create archive",
    'ElFinder_Error_Extract_Files_Archive' : "Unable to extract files from archive",
    'ElFinder_Error_Open_Broken_Link' : "Unable to open broken link",
    'ElFinder_Url_Disabled_By_Config' : "File URL disabled by connector config",
    'ElFinder_Items' : "items",
    'ElFinder_Selected_Items' : "selected items",
    'ElFinder_Back' : "Back",
    'ElFinder_Reload' : "Reload",
    'ElFinder_Open' : "Open",
    'ElFinder_Preview_Quick_Look' : "Preview with Quick Look",
    'ElFinder_Select_File' : "Select file",
    'ElFinder_New_Folder' : "New folder",
    'ElFinder_New_Txt_File' : "New text file",
    'ElFinder_Upload_Files' : "Upload files",
    'ElFinder_Copy' : "Copy",
    'ElFinder_Cut' : "Cut",
    'ElFinder_Paste' : "Paste",
    'ElFinder_Dup' : "Duplicate",
    'ElFinder_Rem' : "Remove",
    'ElFinder_Rename' : "Rename",
    'ElFinder_Edit_Txt_File' : "Edit text file",
    'ElFinder_View_As_Icon' : "View as icons",
    'ElFinder_View_As_List' : "View as list",
    'ElFinder_Resize_Img' : "Resize image",
    'ElFinder_Create_Arch' : "Create archive",
    'ElFinder_Uncompress_Arch' : "Uncompress archive",
    'ElFinder_Get_Info' : "Get info",
    'ElFinder_Help' : "Help",
    'ElFinder_Dock_Undock_Flmgr_Win' : "Dock/undock filemanger window",
    'ElFinder_Max_Allowed_File_Size' : "Maximum allowed files size",
    'ElFinder_Add_Field' : "Add field",
    'ElFinder_File_Info' : "File info",
    'ElFinder_Folder_Info' : "Folder info",
    'ElFinder_Name' : "Name",
    'ElFinder_Kind' : "Kind",
    'ElFinder_Size' : "Size",
    'ElFinder_Modified' : "Modified",
    'ElFinder_Permissions' : "Permissions",
    'ElFinder_Link_To' : "Link to",
    'ElFinder_Dimensions' : "Dimensions",
    'ElFinder_Confirm_Required' : "Confirmation required",
    'ElFinder_Confirm_Rem_Files' : "Are you sure you want to remove files?\u003cbr /\u003e This cannot be undone!",
    'ElFinder_Priv_Read' : "read",
    'ElFinder_Priv_Write' : "write",
    'ElFinder_Priv_Remove' : "remove",
    'ElFinder_Month_Jan' : "Jan",
    'ElFinder_Month_Feb' : "Feb",
    'ElFinder_Month_Mar' : "Mar",
    'ElFinder_Month_Apr' : "Apr",
    'ElFinder_Month_May' : "May",
    'ElFinder_Month_Jun' : "Jun",
    'ElFinder_Month_Jul' : "Jul",
    'ElFinder_Month_Aug' : "Aug",
    'ElFinder_Month_Sep' : "Sep",
    'ElFinder_Month_Oct' : "Oct",
    'ElFinder_Month_Nov' : "Nov",
    'ElFinder_Month_Dec' : "Dec",
    'ElFinder_Day_Tday' : "Today",
    'ElFinder_Day_Yday' : "Yesterday",
    'ElFinder_Unknown' : "Unknown",
    'ElFinder_Folder' : "Folder",
    'ElFinder_Alias' : "Alias",
    'ElFinder_Broken_Alias' : "Broken alias",
    'ElFinder_Plain_Txt' : "Plain text",
    'ElFinder_PostScript_Doc' : "Postscript document",
    'ElFinder_Application' : "Application",
    'ElFinder_MS_Off_doc' : "Microsoft Office document",
    'ElFinder_MS_Word_Doc' : "Microsoft Word document",
    'ElFinder_MS_Excel_Doc' : "Microsoft Excel document",
    'ElFinder_MS_PPT_Doc' : "Microsoft Powerpoint presentation",
    'ElFinder_Open_Off_Doc' : "Open Office document",
    'ElFinder_Flash_App' : "Flash application",
    'ElFinder_Xml_Doc' : "XML document",
    'ElFinder_Bitt_File' : "Bittorrent file",
    'ElFinder_Sevenz_Archive' : "7z archive",
    'ElFinder_Tar_Arch' : "TAR archive",
    'ElFinder_Gzip_Arch' : "GZIP archive",
    'ElFinder_Bzip_Arch' : "BZIP archive",
    'ElFinder_Zip_Arch' : "ZIP archive",
    'ElFinder_Rar_Arch' : "RAR archive",
    'ElFinder_Js_App' : "Javascript application",
    'ElFinder_Php_Src' : "PHP source",
    'ElFinder_Html_Doc' : "HTML document",
    'ElFinder_Js_Src' : "Javascript source",
    'ElFinder_Css_Ss' : "CSS style sheet",
    'ElFinder_C_Src' : "C source",
    'ElFinder_Cpp_Src' : "C++ source",
    'ElFinder_Unix_Ss' : "Unix shell script",
    'ElFinder_Python_Src' : "Python source",
    'ElFinder_Java_Src' : "Java source",
    'ElFinder_Ruby_Src' : "Ruby source",
    'ElFinder_Perl_Scr' : "Perl script",
    'ElFinder_Bmp_Img' : "BMP image",
    'ElFinder_Jpeg_Img' : "JPEG image",
    'ElFinder_Gif_Img' : "GIF Image",
    'ElFinder_Png_Img' : "PNG Image",
    'ElFinder_Tiff_Img' : "TIFF image",
    'ElFinder_Tga_Img' : "TGA image",
    'ElFinder_Adobe_Ps_Img' : "Adobe Photoshop image",
    'ElFinder_Mpeg_Aud' : "MPEG audio",
    'ElFinder_Midi_Aud' : "MIDI audio",
    'ElFinder_Ogg_Vrb_Aud' : "Ogg Vorbis audio",
    'ElFinder_Mp4_Aud' : "MP4 audio",
    'ElFinder_Wav_Aud' : "WAV audio",
    'ElFinder_Dv_Vid' : "DV video",
    'ElFinder_Mp4_Vid' : "MP4 video",
    'ElFinder_Mpeg_Vid' : "MPEG video",
    'ElFinder_Avi_Vid' : "AVI video",
    'ElFinder_Qt_Vid' : "Quicktime video",
    'ElFinder_Wm_Vid' : "WM video",
    'ElFinder_Flash_Vid' : "Flash video",
    'ElFinder_Matr_Vid' : "Matroska video",
    'ElFinder_Select_All_Files' : "Select all files",
    'ElFinder_Ctrl_C_X_V_Files' : "Copy/Cut/Paste files",
    'ElFinder_Open_Selected_File_Folder' : "Open selected file/folder",
    'ElFinder_Open_Close_Ql_Win' : "Open/close QuickLook window",
    'ElFinder_Rem_Selected_Files' : "Remove selected files",
    'ElFinder_Selected_File_Dir_Info' : "Selected files or current directory info",
    'ElFinder_Create_New_Dir' : "Create new directory",
    'ElFinder_Open_Upload_File_Form' : "Open upload files form",
    'ElFinder_Select_Prev_File' : "Select previous file",
    'ElFinder_Select_Next_File' : "Select next file",
    'ElFinder_Ret_Prev_Folder' : "Return into previous folder",
    'ElFinder_Incr_Decr_File_Selection' : "Increase/decrease files selection",
    'ElFinder_Authors' : "Authors",
    'ElFinder_Sponsors' : "Sponsors",
    'ElFinder_Elf_Web_FileMgr' : "elFinder: Web file manager",
    'ElFinder_Version' : "Version",
    'ElFinder_Copy_Right_Std42Ltd' : "Copyright: Studio 42 LTD",
    'ElFinder_Donate_Supp_ProjDev' : "Donate to support project development",
    'ElFinder_Js_Php_Prog' : "Javascripts/PHP programming",
    'ElFinder_Python_Prg_Supp' : "Python programming, techsupport",
    'ElFinder_Design' : "Design: Valentin Razumnih",
    'ElFinder_Spanish_Loc' : "Spanish localization",
    'ElFinder_Icons' : "Icons",
    'ElFinder_License_Bsd' : "License: BSD License",
    'ElFinder_Elf_Doc' : "elFinder documentation",
    'ElFinder_Simple_Useful_Cms' : "Simple and useful content management system",
    'ElFinder_Supp_Proj_Dev_info' : "Support project development and we will place here info about you",
    'ElFinder_Contact_Elf_Int' : "Contacts us if you need help integrating elFinder in you products",
    'ElFinder_Elf_Shortcut_Supp' : "elFinder support following shortcuts",
    'ElFinder_Help_Txt' : "helpText",
    'ElFinder_Chezh_Loc' : "",
    'ElFinder_Chinese_Trad_Loc' : "",
    'ElFinder_Dutch_Loc' : "",
    'ElFinder_Greek_Loc' : "",
    'ElFinder_Hungarian_Loc' : "",
    'ElFinder_Italian_Loc' : "",
    'ElFinder_Latvian_Loc' : "",
    'ElFinder_Poland_Loc' : "",
    'CKEditor_CmsTemplate_Fullsource' : "Full Source",
    'CKEditor_CmsTemplate_Include' : "Include",
    'CKEditor_CmsTemplate_Templatelabel' : "Template",
    'CKEditor_CmsTemplate_Insertlabel' : "Insert",
    'CKEditor_CmsTemplate_Previewlabel' : "Preview",
    'CKEditor_CmsTemplate_Toolbar' : "Insert template",
    'CalendarControl_Today_Button' : "Today",
    'CalendarControl_YearViewToggleButton' : "Year",
    'CalendarControl_MonthViewToggleButton' : "Month",
    'CalendarControl_WeekViewToggleButton' : "Week",
    'CalendarControl_DownloadTitleLink' : "Download this calendar",
    'CalendarControl_LoadingError' : "There was a problem loading data for this calendar.",
    'Close_DefaultText': "Close",
    'ADX_CommunityForumPost_DeleteEntireThread_Warning' : "Warning: Deleting the first post will delete the entire thread.",
    'Sort_Descending_Order' : "sort descending",
    'Sort_Ascending_Order' : "sort ascending",
    'Search_Results' : "Search Results",
    'CKEditor_Page_Header_Style' : "Page header",
    'CKEditor_Alert_Info_Style' : "Alert (Info)",
    'CKEditor_Alert_Success_Style' : "Alert (Success)",
    'CKEditor_Alert_Warning_Style' : "Alert (Warning)",
    'CKEditor_Alert_Danger_Style' : "Alert (Danger)",
    'CKEditor_Well_Style' : "Well",
    'CKEditor_Well_Small_Style' : "Well (Small)",
    'CKEditor_Well_Large_Style' : "Well (Large)",
    'CKEditor_Label_Style' : "Label",
    'CKEditor_Label_Info_Style' : "Label (Info)",
    'CKEditor_Label_Success_Style' : "Label (Success)",
    'CKEditor_Label_Warning_Style' : "Label (Warning)",
    'CKEditor_Label_Danger_Style' : "Label (Danger)",
    'CKEditor_Code_Style' : "Code",
    'CKEditor_Code_Block_Style' : "Code block",
    'CkEditor_iFrame_Title': "Content required field with the field type.",
    'Sort_Ascending_Order' : "sort ascending",
    'Required_Field_Error' : "{0} is a required field.",
    'MaxLength_Validation_Error': "{0} exceeds the maximum length of {1} characters.",
    'Invalid_Error': "{0} is not valid.",
    'Invalid_Date_Format_Error': "{0} must have a valid date format.",
    'Invalid_Decimal_Value_Error': "{0} must be a valid decimal value.",
    'Invalid_Floating_Point_Value_Error': "{0} must be a valid floating-point value.",
    'Invalid_Integer_Value_Error': "{0} must be a valid integer value.",
    'Invalid_Range_Error': "{0} must have a value between {1} and {2}.",
    'Invalid_Email_Address_Error': "{0} must be a valid email address.",
    'Search_DefaultText' : "Search",
    'Home_DefaultText' : "Home",
    'Found_My_Answer' : "Found my answer",
    'Forums_DefaultText' : "Forums",
    'Blogs_DefaultText' : "Blogs",
    'Events_DefaultText' : "Events",
    'Ideas_Label' : "Ideas",
    'Issues_Label' : "Issues",
    'Knowledge_Base_Label' : "Knowledge Base",
    'DropDown_DefaultText' : "DropDown",
    'FileUpload_Browse_Button_Text' : "Attach a file...",
    'SiteMarker_WarningMessage' : "This {0} is associated with the sitemarker {1}. Site functionality may depend on this association. ",
    'SiteMarkers_WarningMessage' : "This {0} is associated with the sitemarkers {1}. Site functionality may depend on this association. ",
    'Validation_PartialUrl_Suffix' : "HTTP is not allowed for partial URL",
    'Cases_Label' : "Cases",
    'Forums_Label' : "Forums",
    'Events_Label' : "Events",
    'Blogs_Label' : "Blogs",
    'ActionLink_Aria_Label' :  "action menu",
    'Access_Denied_Error' :  "You don\u0027t have the appropriate permissions.",
    'Facet_Rating_Four_And_Up' :  "Four stars \u0026 up",
    'Facet_Rating_Three_And_Up' :  "Three stars \u0026 up",
    'Facet_Rating_Two_And_Up' :  "Two stars \u0026 up",
    'Facet_Rating_One_And_Up' :  "One star \u0026 up",
    'Visualization_Chart_Loading_Message' :  "Loading...",
    'Visualization_Chart_NoData_Message' :  "No data available.",
    'Label_For_ActionLink' : "action menu",
    'Validation_ChildPage_PartialUrl_NotSlash_Message' : "Please enter a valid partial URL with alphabets, numbers, and hyphens or underscores",
    'Validation_ChildPage_PartialUrl_NotUnique_Message' : "Web page with same partial url already exists.", 
    'Validation_HomePage_PartialUrl_NotSlash_Message' : "Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.",
    'Pagination_First_Page' : "First page",
    'Pagination_Last_Page' : "Last page",
    'Pagination_Next_Page' : "Next page",
    'Pagination_Previous_Page' : "Previous page",
    'Pagination_Current_Page' : "Current page {0}",
    'Remove_DefaultText' : "Remove",
    'CustomerService_Support_ClearButton' : "Clear",
    'Loading_Message' : "Loading",
    'Download_Button_Label' : "Download",
    'Next_Button_Text' : "Next",
    'Previous_Button_Label' : "Previous",
    'Add_Files' : "Add files",
    'Adding_Files' : "Uploading files...",
    'All' : "All",
    'Sharepoint_File_Size_Not_Supported' : "One or more files are larger than the maximum allowed file size of {0} MB.",
    'Sharepoint_Total_File_Size_Not_Supported' : "The total file size exceeds the maximum allowed limit of {0} MB per upload.",
    'Edit_In_Modern_CMS' : "New Editor",
    'Edit_In_Modern_CMS_Title' : "Try our new editor!",
    'Template_File_Local' : "Local",
    'Template_File_Portal_Components' : "Portal components",
    'Template_File_Web_Template' : "Web templates",
    'Dynamics_365_Portal' : "Dynamics 365 Portal Editor",
    'New_Editor_Preview_Label' : "A new and simplified content editor is available for portal customization.",
    'CMS_Preview_Button' : "Try new editor",
    'ReportContent_Is_Required_Field_Error' : "Report content is a required field.",
    'Load_More_Pages' : "Load more pages",
    'Idea_Voting_Success_Message':"Voted successfully. Total vote count is: {0}",
    'CkEditor_Aria_Label':"Rich Text Editor",
    'Default_Error_Permission':"You don\u0027t have permission to perform this operation.",
    'Aria_Label_And_Title_For_Checkbox' :  "Checkbox",
    'Aria_Label_For_Checkbox' :  "Select or deselect the row",
    'SearchCountText' : "records found",
    'Length_ErrorText' :  "You’ve reached the maximum characters allowed in this field.",
    'Toggle_Filter_Name' :  "Toggle to filter by related company name",
    'Today_Date' :  "Today Date",
    'Selected_Date' :  "Selected Date",
    'Go_To_Today' :  "Go to today",
    'Clear_Selection' :  "Clear selection",
    'Close_The_Picker' :  "Close the picker",
    'Select_Month' :  "Select month",
    'Previous_Month' :  "Previous month",
    'Next_Month' :  "Next month",
    'Select_Year' :  "Select year",
    'Previous_Year' :  "Previous year",
    'Next_Year' :  "Next year",
    'Select_Decade' :  "Select decade",
    'Previous_Decade' :  "Previous decade",
    'Next_Decade' :  "Next decade",
    'Previous_Century' :  "Previous century",
    'Next_Century' :  "Next century",
    'Pick_Hour' :  "Pick hour",
    'Increment_Hour' :  "Increment hour",
    'Decrement_Hour' :  "Decrement hour",
    'Pick_Minute' :  "Pick minute",
    'Increment_Minute' :  "Increment minute",
    'Decrement_Minute' :  "Decrement minute",
    'Pick_Second' :  "Pick second",
    'Increment_Second' :  "Increment second",
    'Decrement_Second' :  "Decrement second",
    'Toggle_Period_AM_PM' :  "Toggle period AM/PM",
    'Select_Time' :  "Select time",
    'Select_Date' :  "Select date",
    'Select_Column_Header_Text' :  "Select",
    'Entitylist_Error_Text_For_Offline_Experience' : "You\u0027re not connected to the internet. Connect to see this list.",
    'Default_Grid_Empty_Message' : "There are no records to display.",
    'Lookup_SingleSelection_Text' : "Choose one record and click Select to continue",
    'PowerBI_Report_Title' : "Power BI report",
    'Modal_Dialog' : "Dialog",
    'Image_Uploaded_Successfully' : "Image uploaded successfully",
    'Image_Deleted_Successfully' : "Image deleted successfully",
    'File_Deleted_Successfully' : "File deleted successfully.",
    'MaxSize_Image_Exceeded' : "Image is too large to upload. The maximum supported image size is {0} MB.",
    'Max_Attachment_Limit_Exceeded' : "The total size of all attachments exceeds the supported file limit of 128 MB",
    'MaxSize_File_Error' : "File is too large to upload. The maximum supported file size is {0} MB.",
    'MinSize_File_Error' : "This file is empty, please upload a valid file.",
    'Text_For_Choose_File' : "Choose File",
    'Text_For_Change_File' : "Change File",
    'Text_For_No_File' : "No file selected",
    'Pressed' : "Pressed",
    'Pva_Privacy_Message' : "Bot responses are AI-generated so inaccuracies are possible.",
    'Completed' : "Completed"
   };